### PR TITLE
Update to Core 0.4

### PR DESCRIPTION
**Pull request by sjmiles**
This is an (incomplete) updating of Font Picker to use Arcsjs Core 0.4.

### CODE REVIEW

**Comment by sjmiles** [comment]
Seems like I messed up the Github Actions. I also built this *up* ... iow I didn't intentionally delete properties (e.g. Ibis). 

I'm hoping you (Ray) can help me restore full functionality!

**Comment by shaper** [comment]
It looks like the vs code demo may have been removed here, we do want to keep that around if we can. Whether it's follow-up for @cromwellian or otherwise, I wanted to mention. Ray, you could add it to the issue tracker.

**Comment by shaper** [comment]
Also (and first and foremost) thank you for doing this! @cromwellian I defer to you for code review, discussion, merge, etc.

**Comment by sjmiles** [comment]
Ack.

**Pull request closed without merging**
